# Generated by Django 4.0.6 on 2022-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
