# Generated by Django 4.0.6 on 2022-08-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_uinfo_bio_uinfo_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='UInfo',
        ),
    ]
