# Generated by Django 4.0.6 on 2022-08-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='body',
        ),
        migrations.AddField(
            model_name='habit',
            name='habit_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
