# Generated by Django 4.0.6 on 2023-01-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
